import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";
// import localFont from "next/font/local";
import Header from "@/app/components/Header/Header";
import BootstrapProvider from "@/app/components/BootstrapProvide";
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const f1 = localFont({
//   src: "./fonts/micross.woff",
//   variable: "--ms",
// });
// const f2 = localFont({
//   src: "./fonts/Calibri.ttf",
//   variable: "--c",
// });
// const f3 = localFont({
//   src: "./fonts/calibril.ttf",
//   variable: "--cl",
// });
// const f4 = localFont({
//   src: "./fonts/calibrib.ttf",
//   variable: "--cb",
// });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <BootstrapProvider>
          <Header />
          {children}
        </BootstrapProvider>
      </body>
    </html>
  );
}
